spring.application.name=quanlydaotao


spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=quanlysinhvien;encrypt=true;trustServerCertificate=true;sslProtocol=TLSv1}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=123123
spring.datasource.driver-class-name=${DB_DRIVER:com.microsoft.sqlserver.jdbc.SQLServerDriver}


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true


server.port=8080
